version: '3.7'

services:
  esloader:
    build: ./search
    environment:
      #full set of labels
      - S3_LABEL_TARBALL=http://loci-assets.s3.ap-southeast-2.amazonaws.com/location_labels/loc-labels-es-json.tar.gz
      #test set of labels
      #- S3_LABEL_TARBALL=http://loci-assets.s3.ap-southeast-2.amazonaws.com/location_labels/loc-labels-es-json-testdata.tar.gz
    command: sh -c './wait-for-it.sh elasticsearch:9200 -t 0 -- ./load_es.sh'
    #command: tail -f /dev/null

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.cors.allow-origin=*"
      - "http.cors.enabled=true"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
#    networks:
#      - esnet
#  kibana:
#    image: docker.elastic.co/kibana/kibana:6.3.1
#    ports:
#      - 5601:5601
#    environment:
#      - "SERVER_NAME=localhost"
#      - xpack.security.enabled=false
  #  networks:
  #    - esnet

volumes:
  esdata1:
   driver: local

#networks:
#  default:
